### PR TITLE
Add aboutus entry

### PR DESCRIPTION
**Pull request by jiangyue12392**

### CODE REVIEW

**Review by Meg1456 — APPROVED** [review]
This looks great! Since its alphabetical, I guess I'll be Teammate C. 
Also, just wondering whether this picture size is big enough? Maybe we can decide a standard once we have all filled in the section..

**Review by Meg1456 — COMMENTED** [review]
Also, shall we insert a picture of ourselves? Or just anything we want?

**Review by Reine0017 — APPROVED** [review]
Looks great!

**Comment by Reine0017** [comment]
> Also, shall we insert a picture of ourselves? Or just anything we want?

@Meg1456 Either works hahaa :))

**Pull request merged**
