### PR TITLE
Added entry to aboutus.html and added picture

### PR DESCRIPTION
**Pull request by Reine0017**
Hi Guys! I've added my entry in the aboutus.html page and added an image of myself too.

### CODE REVIEW

**Comment by jiangyue12392** [comment]
Aboutus page looks good to me. I am not sure about whether we want to push our local changes of the index.html page since its content overlaps with aboutus page. What do you think?

**Comment by Reine0017** [comment]
Oh riiight okkay I'll remove it right after I get off work! Thanks for the suggestion :)

**Comment by Reine0017** [comment]
Hi guys! Was just wondering if you guys wanna use this version or the beta version (React)

**Comment by Reine0017** [comment]
Okay! My entry in the index.html page is removed.

**Review by jiangyue12392 — APPROVED** [review]
Cool, nice image.

**Comment by Meg1456** [comment]
Looks good to me! I have made my changes in the current version. Will push that first. Shall we switch to React once all our 'About Us' edits have been merged?

**Pull request merged**
