### PR TITLE
Created FAQ Page + Modify icon on landing page

### PR DESCRIPTION
**Pull request by Meg1456**

### CODE REVIEW

**Comment by jiangyue12392** [comment]
Hi Meg, I think your PR has way too many wrong indent changes. It is hard to review this PR as I can't really find the actual code changes. Can you resolve the indent issue first?

**Comment by Meg1456** [comment]
> Hi Meg, I think your PR has way too many wrong indent changes. It is hard to review this PR as I can't really find the actual code changes. Can you resolve the indent issue first?

Hey, so sorry about that! The IDE takes care of all the indentation, but I didn't realise that the flip side to that is that the git commit would have these superfluous changes as well. I'm not sure if I can change this commit now?

**Comment by jiangyue12392** [comment]
Hi @Meg1456 , Can you configure your IDE so that it does 2 space indent instead of 4? You can use IDE for auto-indent, but please configure it so that it conforms to our 2 space indent convention

**Comment by Meg1456** [comment]
> Hi @Meg1456 , Can you configure your IDE so that it does 2 space indent instead of 4? You can use IDE for auto-indent, but please configure it so that it conforms to our 2 space indent convention

Ok sure, will do!

**Comment by Meg1456** [comment]
@jiangyue12392 I have changed it now and resolved merged conflict

**Review by jiangyue12392 — APPROVED** [review]
Looks good to me!

**Pull request merged**
